### ISSUE TITLE
Not using the official wordlist

### ISSUE THREAD

**Issue by MoxAssault** [Douile/wordament-solver#1]
**Describe the bug**
The list of words produced is not accurate. Here is a recent example. 

Sowder
Gowder
Owlier

These all came up on my last puzzle and none of them worked. I don't use this often, except on Expert puzzles that include only a couple vowels, but it has been failing multiple words. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Enviroment**
OS: Windows 10 x64

**Additional context**

**Comment by Douile** [comment]
This is due to using a generic English wordlist instead of the actual wordament dictionary
